[tool.poetry]
name = "bb-webscrapp"
version = "0.1.0"
description = "Baixa extatos bancários do Banco do Brasil"
authors = ["Vinicius Maciel"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
blue = "^0.8.0"
isort = "^5.10.1"
prospector = "^1.7.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
